### ISSUE TITLE
Finding information about a scene's items and random fairy selection

### ISSUE THREAD

**Issue by TyzoneLyraNature** [Helco/zzdocs#2]
I'm finding information here describing the different groups of random fairy selections used throughout the game: https://helco.github.io/zzdocs/internal/randomFairySelection/

However I'm not sure where this information is used in the files (doesn't seem to be in any .fbs files). I'm guessing this might be part of the .scn files, but I'm not quite sure where to go from there. Likewise, I'm wondering how to find information on the placement of items in scenes, or which items can be found in chests? (My goal would be to shuffle around the items within certain chests, or the pools of fairies found within each area).

**Comment by Helco** [comment]
the fairy groups are used for:
  -  `NpcAttackPosition` triggers, so these are stored in the [scene files](https://helco.github.io/zzdocs/resources/SCN/SCN_Trigger/)
  -  the script command `defaultWizform`, which only applies to NPC init and update scripts so they are stored in [fb0x05.fbs](https://helco.github.io/zzdocs/resources/FBS/fb0x05/)

For the items that are part of the scene, each item is a [scene model](https://helco.github.io/zzdocs/resources/SCN/SCN_Model/) with a [Collectable behavior](https://helco.github.io/zzdocs/internal/Behaviors/#collectable) attached to it. The filename of the model signifies the item ID.

Chests are actually regular NPCs, so which item they will give depends on the NPC ID (which is the first parameter of the `NpcStartpoint` trigger) and the script that is executed where you will probably find a [`givePlayerCards`](https://helco.github.io/zzdocs/internal/script%20commands/givePlayerCards/) command.
I think Funatics used a single NPC for all chests and use the NPC modifier (second parameter of the trigger) in a big if-else structure.

Looking through this it is obvious I should probably update the documentation a bit more as a lot of known stuff is missing or outdated...
